[api]
enabled = true
# Port for local dev - 'supabase functions serve'
port = 54321

[db]
# If you are using Supabase hosted - this is pulled from linked project
major_version = 15

[studio]
enabled = false
