// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetadataService fronts one filesystem.Service with DTO-only results.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateFolder creates one available folder and returns its DTO.
 */
export function CreateFolder(vaultID: string, parentID: string | null, name: string): $CancellablePromise<$models.EntryDTO> {
    return $Call.ByID(952457637, vaultID, parentID, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateLocalVault creates a metadata-only vault and returns its DTO.
 */
export function CreateLocalVault(name: string): $CancellablePromise<$models.VaultDTO> {
    return $Call.ByID(4027016116, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteFolder removes one folder, recursively with its subtree when
 * recursive, and returns an error only.
 */
export function DeleteFolder(entryID: string, recursive: boolean): $CancellablePromise<void> {
    return $Call.ByID(535989922, entryID, recursive);
}

/**
 * GetVault returns one metadata-only vault DTO by ID.
 */
export function GetVault(id: string): $CancellablePromise<$models.VaultDTO> {
    return $Call.ByID(2301875473, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListEntries returns the single-level children DTOs of one parent (vault
 * root when parentID is nil), never nil.
 */
export function ListEntries(vaultID: string, parentID: string | null): $CancellablePromise<$models.EntryDTO[]> {
    return $Call.ByID(3069639255, vaultID, parentID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListVaults returns every metadata-only vault oldest-first, never nil.
 */
export function ListVaults(): $CancellablePromise<$models.VaultDTO[]> {
    return $Call.ByID(1231275552).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * MoveEntry re-parents one entry and returns its DTO.
 */
export function MoveEntry(entryID: string, parentID: string | null): $CancellablePromise<$models.EntryDTO> {
    return $Call.ByID(917092264, entryID, parentID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RenameEntry renames one entry and returns its DTO.
 */
export function RenameEntry(entryID: string, name: string): $CancellablePromise<$models.EntryDTO> {
    return $Call.ByID(1354098909, entryID, name).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.EntryDTO.createFrom;
const $$createType1 = $models.VaultDTO.createFrom;
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $Create.Array($$createType1);
