// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EntryDTO is the presentation shape of one entry tree node. Size renders
 * as a decimal string so large int64 values survive JSON numbers exactly;
 * a nil parent (vault root) and a nil MIME type stay JSON null.
 */
export class EntryDTO {
    "id": string;
    "vault_id": string;
    "parent_id": string | null;
    "kind": string;
    "name": string;
    "status": string;
    "size": string;
    "mime_type": string | null;
    "created_at": string;
    "updated_at": string;

    /** Creates a new EntryDTO instance. */
    constructor($$source: Partial<EntryDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("vault_id" in $$source)) {
            this["vault_id"] = "";
        }
        if (!("parent_id" in $$source)) {
            this["parent_id"] = null;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = "";
        }
        if (!("mime_type" in $$source)) {
            this["mime_type"] = null;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntryDTO($$parsedSource as Partial<EntryDTO>);
    }
}

/**
 * VaultDTO is the presentation shape of a metadata-only vault: identity,
 * naming, and timestamps only, never key-bearing material.
 */
export class VaultDTO {
    "id": string;
    "name": string;
    "backend_type": string;
    "state": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new VaultDTO instance. */
    constructor($$source: Partial<VaultDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("backend_type" in $$source)) {
            this["backend_type"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultDTO($$parsedSource as Partial<VaultDTO>);
    }
}
