// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ClearCompletedTransfers() {
  return window['go']['main']['App']['ClearCompletedTransfers']();
}

export function CreateFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3, arg4);
}

export function CreateSyncFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateSyncFolder'](arg1, arg2);
}

export function CreateWebhookShard(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateWebhookShard'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DeleteSyncFolder(arg1) {
  return window['go']['main']['App']['DeleteSyncFolder'](arg1);
}

export function DeleteWebhookShard(arg1) {
  return window['go']['main']['App']['DeleteWebhookShard'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function DownloadFileWithDialog(arg1) {
  return window['go']['main']['App']['DownloadFileWithDialog'](arg1);
}

export function ExportMetadata() {
  return window['go']['main']['App']['ExportMetadata']();
}

export function GenerateShareLink(arg1) {
  return window['go']['main']['App']['GenerateShareLink'](arg1);
}

export function GetFile(arg1) {
  return window['go']['main']['App']['GetFile'](arg1);
}

export function GetFileDetails(arg1) {
  return window['go']['main']['App']['GetFileDetails'](arg1);
}

export function GetGatewaysStatus() {
  return window['go']['main']['App']['GetGatewaysStatus']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStreamURL(arg1) {
  return window['go']['main']['App']['GetStreamURL'](arg1);
}

export function GetTransfers() {
  return window['go']['main']['App']['GetTransfers']();
}

export function ListFiles(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}

export function ListSyncFolders() {
  return window['go']['main']['App']['ListSyncFolders']();
}

export function ListWebhookShards() {
  return window['go']['main']['App']['ListWebhookShards']();
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function RestoreFile(arg1) {
  return window['go']['main']['App']['RestoreFile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchFiles(arg1) {
  return window['go']['main']['App']['SearchFiles'](arg1);
}

export function SelectAndUploadFiles(arg1) {
  return window['go']['main']['App']['SelectAndUploadFiles'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SyncFoldersNow() {
  return window['go']['main']['App']['SyncFoldersNow']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UpdateSyncFolder(arg1) {
  return window['go']['main']['App']['UpdateSyncFolder'](arg1);
}

export function UpdateWebhookShard(arg1) {
  return window['go']['main']['App']['UpdateWebhookShard'](arg1);
}

export function UploadFiles(arg1, arg2) {
  return window['go']['main']['App']['UploadFiles'](arg1, arg2);
}

export function ValidateWebhook(arg1) {
  return window['go']['main']['App']['ValidateWebhook'](arg1);
}
