// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {main} from '../models';
import {discord} from '../models';

export function CancelTransfer(arg1:string):Promise<boolean>;

export function ClearCompletedTransfers():Promise<void>;

export function CreateFolder(arg1:any,arg2:string,arg3:string,arg4:string):Promise<storage.Folder>;

export function CreateSyncFolder(arg1:string,arg2:any):Promise<storage.SyncFolder>;

export function CreateWebhookShard(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<storage.WebhookShard>;

export function DeleteFile(arg1:string,arg2:boolean):Promise<void>;

export function DeleteFolder(arg1:string,arg2:boolean):Promise<void>;

export function DeleteSyncFolder(arg1:string):Promise<void>;

export function DeleteWebhookShard(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function DownloadFileWithDialog(arg1:string):Promise<string>;

export function ExportMetadata():Promise<string>;

export function GenerateShareLink(arg1:string):Promise<Record<string, string>>;

export function GetFile(arg1:string):Promise<storage.File>;

export function GetFileDetails(arg1:string):Promise<storage.File>;

export function GetGatewaysStatus():Promise<Record<string, any>>;

export function GetPlatform():Promise<string>;

export function GetSettings():Promise<storage.AppSettings>;

export function GetStats():Promise<storage.StorageStats>;

export function GetStreamURL(arg1:string):Promise<string>;

export function GetTransfers():Promise<Array<storage.Transfer>>;

export function ListFiles(arg1:any,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<main.FileListResult>;

export function ListFolders(arg1:any):Promise<Array<storage.Folder>>;

export function ListSyncFolders():Promise<Array<storage.SyncFolder>>;

export function ListWebhookShards():Promise<Array<storage.WebhookShard>>;

export function MoveFile(arg1:string,arg2:any):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function RestoreFile(arg1:string):Promise<void>;

export function SaveSettings(arg1:storage.AppSettings):Promise<void>;

export function SearchFiles(arg1:string):Promise<Array<storage.File>>;

export function SelectAndUploadFiles(arg1:any):Promise<Array<storage.File>>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SyncFoldersNow():Promise<void>;

export function ToggleFavorite(arg1:string):Promise<boolean>;

export function UpdateSyncFolder(arg1:storage.SyncFolder):Promise<void>;

export function UpdateWebhookShard(arg1:storage.WebhookShard):Promise<void>;

export function UploadFiles(arg1:any,arg2:Array<string>):Promise<Array<storage.File>>;

export function ValidateWebhook(arg1:string):Promise<discord.WebhookInfo>;
